

const TCOnlineBooking = () => {
    return (
        <div>
                <div>
                <h1 className="text-3xl font-semibold">T&C of Online Booking</h1>
                <p>Terms and Conditions for online booking of Car with an authorized dealer of Hyundai Motor India Limited</p>
                </div>
            <ul className="list-inside list-decimal space-y-6">
                <li>
                &#34;Customer&#34; means any Individual / Firm / Proprietorship / Company etc. competent to enter into contract as per the Indian Contract Act, 1872 and interested in booking of Hyundai Car with a Dealership of Hyundai Motor India Limited (HMIL) through online/website of HMIL by making advance payment using a valid Credit Card/Debit Card/Mobile Banking (IMPS)/Net banking Account.
                </li>
                <li>
                &rdquo;Dealership&rdquo; means any person or entity engaged by HMIL for sale and/or service of the Car(s) manufactured and marketed by HMIL.
                </li>
                <li>
                &rdquo;Car&rdquo; means any models of Vehicles manufactured , imported, marketed or sold through HMIL’s Website for and on behalf of its Dealership or by HMIL to Customers.
                </li>
                <li>
                The online booking system facility provided on HMIL Website (“Website”) will facilitate the Customer in faster booking of the Car only with the Dealership as mentioned in the Website, at their convenience.
                </li>
                <li>
                A customer can book for more than 1 (one) Car and the booking process would be one car per booking.
                </li>
                <li>
                The Customer needs to provide accurate information while making online booking and the information shall be in English language only.
                </li>
                <li>
                The Customer shall obtain the customer copy of the Car order form duly stamped at the Dealership.
                </li>
                <li>Post online booking, the Customer will get a Booking Reference ID (Customer ID) and with that the Customer shall contact the concern Dealership which he/she selected in making online booking, regarding availability of selected variant, balance payment, delivery details etc. Customer is requested to opt one colour choice for a particular variant only. In case of any subsequent change in either colour or variant preference, the old Booking Reference Number shall remain same.</li>
                <h4 className="font-bold">Acceptance of Payment towards Booking</h4>
                <li>For booking online, the Customer is required to pay the specified Booking amount as displayed on the Website at the time of booking of Car selected by the Customer. The Payment of booking amount is to be made online by Credit Card/Debit Card or netbanking through NEFT/RTGS payable in favour of the Dealership.</li>
                <li>Acceptance of online booking payment is taken on behalf of the Dealership by a Payment Gateway (hereinafter referred to as &rdquo;Agency&rdquo;).</li>
                <li>HMIL is only a facilitator in the transaction and has suitably made the Website available for online booking of Car and transfer of amount from Customer account to the Dealership. Hence, HMIL will not be responsible for any charges imposed and action taken by the Agency arising out of online booking payment. In the event, the Customer suffers any kind of loss or damage arising out of the payment transaction made by the Customer on the website, HMIL shall not be responsible for the same and the Customer will have recourse to claim damages only from the Dealership.</li>
                <li>The online booking is available at ________ whereas payment gateway is powered by intermediary providing Payment gateway and merchant services.</li>
                <li>The Payment made by the Customer for online booking of Car through payment gateway Agency is subject to the terms and conditions as provided by the payment gateway Agency. HMIL or its Dealership shall not be responsible for payment issues made in respect of online booking through the payment gateway Agency.</li>
                <li>The transactions, booking amount and all other commercial terms such as balance payment, delivery of Car etc., shall be as per the bipartite contractual obligations agreed between the Customer and the concerned Dealership only and the payment gateway facility is arranged just to facilitate the completion of online booking transaction smooth and speedy. Use of the payment gateway facility shall not render HMIL / Dealership liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after sales or warranty services or fraud as regards the products and /or services listed on HMIL&#39;s Website.</li>
                <li>The booking amount remitted by the Customer will be realised and transferred to the respective Dealership’s account, which the customer selected, on making online booking.</li>
                <li>The Customer authorizes Gateway Payment Agency engaged by HMIL to collect, process, facilitate and remit payments and/or the transaction electronically in respect of transactions through Payment Gateway Facility. The Customer understands, accepts and agrees that the Payment Gateway facility provided by HMIL is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, for the transactions on HMIL Website using the existing authorized banking infrastructure and Payment Gateway networks. By providing Payment Gateway facility, HMIL is neither acting as trustee nor acting in a fiduciary capacity with respect to the transaction or the online Booking amount</li>
                <li>The Processing fees for the online booking payment made by the Customer will be borne by the Dealership, only in case where the online booking is getting converted into a successful sale of delivery of Car to the Customer by the Dealership.</li>
                <li>HMIL reserves the right to restrict the number of online booking which a Customer can make through his/her Credit/Debit/ Card / Bank Account/ or any other financial instrument and accordingly reserve its right to reject an online booking made by a Customer, without assigning any reasons.</li>
                <li>HMIL reserves the right to reject without assigning any reason, an online booking made by a Customer having prior history of questionable charges including without limitation breach of any agreements by Customer with HMIL/ Dealership or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</li>
                <li>HMIL may delay the notification of payment confirmation to Dealership, if HMIL deems suspicious or for Customers conducting high transaction volumes to ensure safety of the Transaction. In addition, HMIL may hold the transaction and may not inform Dealership or remit Booking amount to law enforcement officials (instead of refunding the same to Customer) at the request of law enforcement officials or in the event the Customer is engaged in any form of illegal activity.</li>
                <li>The Customer acknowledges that HMIL will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction or any delay in processing a Transaction which is beyond control of HMIL.</li>
                <li>After online booking of Car and online payment transaction, the system will generate a transaction Reference Number, acknowledging the receipt of payment towards the booking of Car through online. The Customer shall use the Reference Number for all future communication with the Dealership and produce the copy of receipt showing the Reference Number as and when required by the Dealership. However, this Acknowledgement shall not be treated as acceptance of booking by dealership.</li>
                <li>The Customer agrees that the Dealership shall not be deemed to have accepted the booking of the Customer or be bound by the booking until Dealership notifies the Customer of its acceptance of the booking.</li>
                <li>The Booking amount paid by the Customer at the time of online booking will be adjusted against the sale price of the Car at the time of raising the Invoice by the Dealership. The Customer shall pay the balance amount to the Dealership to complete the successful transaction of purchase of the car. Thereupon, the Dealership shall deliver the Car as per the delivery commitment date given by the Dealership. Only after receipt of the full balance price of the Car and submission of requisite supporting documents, the booking will be binding. Until then, the online booking is merely a request on the part of the Customer and an indication of an intention to sell on the part of the Dealership and does not result in a booking confirmation or contract of sale and should the booking fail to be accepted for whatever reasons or could not be completed, there will be no financial implications to HMIL or the Dealership except as per the terms and conditions mentioned here.</li>
                <li>If a Customer fails to pay the balance amount within the stipulated time as informed by the Dealer, the Car chosen by the Customer would be allocated to the next customer. Thereafter, depending on the date of receipt of balance amount from the Customer, the Customer’s Booking Reference Number would change and accordingly delivery of Car booked by the Customer would be postponed by the Dealership, depending on the availability of particular Car booked by the Customer.</li>
                <li>The Vehicle Specification and price including, statutory levies (Import Duty, Excise Duty, Taxes and other levies) will be applicable as prevailing on the date of invoice issued by Dealership to the Customer.</li>
                <h4 className="font-bold">Delivery of Hyundai Car</h4>
                <li>
                The Customer should contact the Dealership selected by him / her at the time of making the online booking for the purpose of taking delivery. The name on which Booking has been made cannot be changed and Dealership will have to raise a special request with HMIL to change Customer name against a Booking
                </li>
                <li>Expected date of Delivery of Car will be confirmed by the Dealership upon receipt of balance sale price from the Customer however the delivery of Car is subject to availability of Car at the selected Dealership. In case, there is a waiting period, the Customer will be informed of the expected date of delivery by the Dealership.</li>
                <li>All the original documents will need to be produced at the time of taking delivery of Car for verification by the respective Dealership.</li>
                <li>The documents required for registration of the Car have to be submitted as per the policy, rules and regulations of the transport authority of the concerned State Government.</li>
                <li>The Delivery of Car shall be made after realization of full payment on the Bank account of the Dealership. Further, the delivery of the Car shall be made after registration number is allotted by the Transport Department. The Customer understands that the registration of the Car is at the sole discretion of the transport authority concerned.</li>
                <h4 className="font-bold">Cancellation and Refund</h4>
                <li>If any online booking amount and other amount paid by the Customer to the Dealership towards the price of the Car, Accessories or statutory requirement, then the Customer has to claim the said amount from the Dealership and no online transaction shall be made in this regard. No cash payments would be made by the Dealership to the Customers.</li>
                <li>In the case of financed orders, cancellation request shall be sent to the Dealership through the financing entity and refunds will be made by the Dealership to the concerned financing entity only.</li>
                <li>The Notice of cancellation should be sent to the Dealership together with the original customer copy of the Order Booking Form if any and the payment receipt. Once cancelled, Customer Order cannot be reinstated at the same Booking Reference Number.</li>
                <h4 className="font-bold">General Terms</h4>
                <li>The Customer shall be responsible for maintaining the confidentiality of the Display Name and Password and for all activities that occur under the Display Name and Password. If the Customer provides any information that is untrue, inaccurate, not correct or incomplete or HMIL has reasonable grounds to suspect that such information is untrue, inaccurate, not correct or incomplete, HMIL shall have the right to indefinitely suspend or terminate or block access of the membership on the Website and refuse to provide the Customer with access to the Website.</li>
                <li>HMIL may from time to time offer promotions/rewards/benefits for booking of Car(s) made through this online, for a limited period. The terms & conditions of such promotions/rewards/ benefits will be specified separately. HMIL may withdraw/change the terms & conditions of promotions/rewards/benefits for online booking at any time without prior notice</li>
                <li>HMIL reserves the right to change the price, model, variants, specifications and features of the Car as shown on the HMIL Website or at the Dealership without any prior notice.</li>
                <li>HMIL reserves the right to change or alter any terms and conditions or the process itself without prior notice and may withdraw the offer of online booking without prior notice.</li>
                <li>HMIL or Dealership will not be responsible for delay, loss or non- receipt of online booking information or any other form of submission not contemplated herein.</li>
                <li>The online Booking is not compulsory, but only optional and voluntary for the interested customers and Cars can be booked and purchased by the Customer directly at HMIL Dealership as well.</li>
                <li>HMIL or Dealership would not be responsible for delay, loss or non-receipt of communication by the Customer due to incorrect address or contact details, given in the Online booking form or any other form of submission not contemplated herein or otherwise. The Customer online booking will be rejected in case of incomplete forms or non-receipt of booking amount.</li>
                <li>HMIL, their Directors, Employees, Dealers, Consultants, assume no liability whatsoever under any circumstances whatsoever for any direct or indirect loss or damage arising from a Customer booking a Car through the online/website of HMIL.</li>
                <li>Customer is advised to quote the Booking Reference number and the date thereof for any enquiry regarding delivery position.</li>
                <li>Delivery is subject to “force majeure” conditions. The term “force majeure” means any circumstances which are unusual, unforeseeable and are beyond the control of HMIL and/or Dealership concerned, the consequence of which could not have been avoided even if all due care had been exercised, including but not limited to acts of god, war or threat of war, riot, civil strike, hostilities, political unrest, government action, industrial dispute, natural or other disaster, nuclear incident, terrorist activity, sabotage, blockage, embargo, weather conditions, transport strike, fire, flood, typhoon, tempest, drought, short supply of labour, fuel, raw material, or manufactured produce, or otherwise preventing or hindering the manufacture or delivery of the car and all similar events beyond the control of HMIL and/or Dealership concerned.</li>
                <li>Customer further understands that the terms and conditions of sale of the Car is exclusively between Customer and Dealership only and that HMIL, which is operating with the Dealership concerned on principal to principal basis relationship, is not bound by any such terms in any manner whatsoever, except in cases where the selected dealership is the showroom owned by HMIL.</li>
                <li>Customer hereby expressly consents HMIL to store/transfer the personal data (i.e. personally identifiable data) that voluntarily supplied herein and process and use it by HMIL as it deems appropriate or shared with its affiliates, Associates, Dealers, Agencies, auditors, legal advisers, marketing partners, Representatives etc. to contact the Customer through outbound call by Telephone/Mobile Numbers or send SMS or Email for offers, marketing and/or promotions, product related information, newsletter, market survey, poll, research, study, programs, enquiries about offerings, services and other legitimate purposes. HMIL may disclose information if required to do so by any law enforcing agency.</li>
                <li>All personal data accumulated will be acquired, processed, and used according to the applicable regulations governing the protection of personal data for the sole purpose of managing and maintaining HMIL’s own legitimate business interests.</li>
                <li>Although HMIL takes reasonable measures to safeguard against unauthorized disclosures of information, it cannot assure that Personal Data that Customer provides will never be disclosed in a manner that is inconsistent with the Policy.</li>
                <li>The Customer shall indemnify and hold harmless HMIL, its, affiliates, subsidiaries, Dealerships (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys&#39; fees, made by any third party or penalty imposed due to or arising out of breach of the terms and conditions, Terms of Use, privacy Policy and other Policies by the Customer, or any act or omission of the Customer or violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) by the Customer.</li>
                <li>In case of any dispute relating to enforcement, interpretation or application of these terms and conditions shall be subject to Arbitration by single arbitrator appointed by HMIL. The venue of Arbitration shall be at New Delhi. The Arbitration Proceedings shall be in accordance with the Arbitration and Conciliation Act, 1996 and its allied rules as amended from time to time. Subject to the Arbitration, the Parties submit to the exclusive jurisdiction of the Courts of the City of the Dealership selected by the Customer for booking Car.</li>
                <li>The terms and conditions of this Online booking shall be governed by the laws as applicable in India.</li>
                <li>By accessing, browsing or otherwise using HMIL Website for booking Car, it is assumed that the Customer has read, understood and accepts and agrees to all the terms and conditions mentioned above on the Website and also gives unconditional consent for being contacted for Products/Services of HMIL over telephone/mobile phone/email/sms. Non-acceptance of any of these terms and conditions will result in disqualification. Further, by impliedly or expressly accepting the Terms of Use, the Customer also accepts and agrees to be bound by HMIL Policies (including but not limited to Privacy Policy available on its Website) as amended from time to time.</li>
            </ul>
        </div>
    );
};

export default TCOnlineBooking;